In [23]:
import numpy as np
import pandas as pd
import seaborn as sns

# Context

In [25]:
titanic_data = pd.read_csv('tested.csv', index_col='PassengerId')
titanic_data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# Data quality assessment

In [27]:
print(f'Shape: {titanic_data.shape}')

Shape: (418, 11)

In [47]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 418 entries, 892 to 1309
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Name      418 non-null    object
 3   Sex       418 non-null    object
 4   Age       332 non-null    float64
 5   SibSp     418 non-null    int64
 6   Parch     418 non-null    int64
 7   Ticket    418 non-null    object
 8   Fare      417 non-null    float64
 9   Cabin     91 non-null     object
 10  Embarked  418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 39.2+ KB

In [29]:
duplicate_rows = titanic_data.loc[titanic_data.duplicated().values]
duplicate_rows_count = duplicate_rows.shape[0]
print(f'Duplicate rows count: {duplicate_rows_count}')

Duplicate rows count: 0

In [57]:
#not-null
survived_not0_percent = titanic_data.loc[pd.notna(titanic_data.Survived)].Survived.shape[0] / titanic_data.Survived.shape[0] * 100
pclass_not0_percent = titanic_data.loc[pd.notna(titanic_data.Survived)].Pclass.shape[0] / titanic_data.Pclass.shape[0] * 100
name_not0_percent = titanic_data.loc[pd.notna(titanic_data.Name)].Name.shape[0] / titanic_data.Name.shape[0] * 100
sex_not0_percent = titanic_data.loc[pd.notna(titanic_data.Sex)].Sex.shape[0] / titanic_data.Sex.shape[0] * 100
age_not0_percent = titanic_data.loc[pd.notna(titanic_data.Age)].Age.shape[0] / titanic_data.Age.shape[0] * 100
sibsp_not0_percent = titanic_data.loc[pd.notna(titanic_data.SibSp)].SibSp.shape[0] / titanic_data.SibSp.shape[0] * 100
parch_not0_percent = titanic_data.loc[pd.notna(titanic_data.Parch)].Parch.shape[0] / titanic_data.Parch.shape[0] * 100
ticket_not0_percent = titanic_data.loc[pd.notna(titanic_data.Ticket)].Ticket.shape[0] / titanic_data.Ticket.shape[0] * 100
fare_not0_percent = titanic_data.loc[pd.notna(titanic_data.Fare)].Fare.shape[0] / titanic_data.Fare.shape[0] * 100
cabin_not0_percent = titanic_data.loc[pd.notna(titanic_data.Cabin)].Cabin.shape[0] / titanic_data.Cabin.shape[0] * 100
embarked_not0_percent = titanic_data.loc[pd.notna(titanic_data.Embarked)].Embarked.shape[0] / titanic_data.Embarked.shape[0] * 100

column_names = titanic_data.columns.tolist()

notnull_percent = pd.DataFrame({'not-null, %': [survived_not0_percent, pclass_not0_percent, name_not0_percent, sex_not0_percent, age_not0_percent, sibsp_not0_percent, 
                                                parch_not0_percent, ticket_not0_percent, fare_not0_percent, cabin_not0_percent, embarked_not0_percent]}, index=[column_names])

notnull_percent = notnull_percent.round(2)
notnull_percent

          not-null, %
Survived       100.00
Pclass         100.00
Name           100.00
Sex            100.00
Age             79.43
SibSp          100.00
Parch          100.00
Ticket         100.00
Fare            99.76
Cabin           21.77
Embarked       100.00

# Data exploration

# Summary